apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverlessdb-operator
  namespace: tidb-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: serverlessdb-operator
  template:
    metadata:
      labels:
        name: serverlessdb-operator
    spec:
      serviceAccountName: serverlessdb-operator
      containers:
        - name: serverlessdb-operator
          # Replace this with the built image name
          image: localhost:5000/serverlessdb-for-htap/serverlessdb-operator:v1.0.0
#          command:
#          - sldb-operator
          args:
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "serverlessdb-operator"
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ROOT_PASSWORD
                  name: serverlessdb-operator
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 300m
              memory: 500Mi
          volumeMounts:
            - mountPath: /usr/local/bin/operator_config.yaml
              subPath: operator_config.yaml
              name: serverlessdb-operator-config
      volumes:
        - name: serverlessdb-operator-config
          configMap:
            name: serverlessdb-operator
            items:
              - key: operator-config
                path: operator_config.yaml
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
