apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"serverlessdb-operator","namespace":"tidb-admin"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"serverlessdb-operator"}},"template":{"metadata":{"labels":{"name":"serverlessdb-operator"}},"spec":{"containers":[{"args":null,"env":[{"name":"WATCH_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"OPERATOR_NAME","value":"serverlessdb-operator"}],"image":"registry.clouddb:5000/clouddb/serverlessdb-operator:v1.0.0-0430","imagePullPolicy":"Always","name":"serverlessdb-operator","resources":{"limits":{"cpu":"500m","memory":"1024Mi"},"requests":{"cpu":"300m","memory":"500Mi"}},"volumeMounts":[{"mountPath":"/usr/local/bin/operator_config.yaml","name":"serverlessdb-operator-config","subPath":"operator_config.yaml"}]}],"nodeSelector":{"node-role.kubernetes.io/master":""},"serviceAccountName":"serverlessdb-operator","tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master","operator":"Exists"}],"volumes":[{"configMap":{"items":[{"key":"operator-config","path":"operator_config.yaml"}],"name":"serverlessdb-operator"},"name":"serverlessdb-operator-config"}]}}}}
  creationTimestamp: "2021-04-29T12:38:11Z"
  generation: 5
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:name: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:name: {}
          f:spec:
            f:containers:
              k:{"name":"serverlessdb-operator"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"OPERATOR_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POD_NAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef:
                        .: {}
                        f:apiVersion: {}
                        f:fieldPath: {}
                  k:{"name":"WATCH_NAMESPACE"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef:
                        .: {}
                        f:apiVersion: {}
                        f:fieldPath: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/usr/local/bin/operator_config.yaml"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:subPath: {}
            f:dnsPolicy: {}
            f:nodeSelector:
              .: {}
              f:node-role.kubernetes.io/master: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:tolerations: {}
            f:volumes:
              .: {}
              k:{"name":"serverlessdb-operator-config"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:items: {}
                  f:name: {}
                f:name: {}
    manager: kubectl
    operation: Update
    time: "2021-05-06T09:52:10Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-05-10T08:54:25Z"
  name: serverlessdb-operator
  namespace: tidb-admin
  resourceVersion: "64520269"
  selfLink: /apis/apps/v1/namespaces/tidb-admin/deployments/serverlessdb-operator
  uid: 57a0a4d6-c6e7-490c-a3e7-79b1114f6f5d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: serverlessdb-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: serverlessdb-operator
    spec:
      containers:
      - command:
        - /usr/local/bin/serverless-operator
        - --config=/usr/local/bin/operator_config.yaml
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: serverlessdb-operator
        image: registry.clouddb:5000/clouddb/sldb-operator:test
        imagePullPolicy: Always
        name: serverlessdb-operator
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/bin/operator_config.yaml
          name: serverlessdb-operator-config
          subPath: operator_config.yaml
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: serverlessdb-operator
      serviceAccountName: serverlessdb-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: operator-config
            path: operator_config.yaml
          name: serverlessdb-operator
        name: serverlessdb-operator-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-04-29T12:38:11Z"
    lastUpdateTime: "2021-05-06T09:52:14Z"
    message: ReplicaSet "serverlessdb-operator-7f74749574" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-10T08:54:25Z"
    lastUpdateTime: "2021-05-10T08:54:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
