apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serverlessdbs.bcrds.cmss.com
spec:
  group: bcrds.cmss.com
  names:
    kind: ServerlessDB
    listKind: ServerlessDBList
    plural: serverlessdbs
    singular: serverlessdb
    shortNames:
      - sl
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ServerlessDB is the Schema for the serverlessdbs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ServerlessDBSpec defines the desired state of ServerlessDB
          properties:
            scaleIn:
              type: string
            scaleOut:
              type: string
            timeToScaleDown:
              type: string
            useTiFlash:
              description: Indicates that the tiflash cluster is used and will not
                be processed by the controller.
              type: boolean
          type: object
        status:
          description: ServerlessDBStatus defines the observed state of ServerlessDB
          properties:
            conditions:
              description: Represents the latest available observations of a cluster's
                state.
              items:
                description: ServerlessDBCondition describes the state of a cluster
                  at a certain point.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of the condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            nodePort:
              additionalProperties:
                format: int32
                type: integer
              description: Node port for sldb
              type: object
            phase:
              description: Represents the latest phase
              type: string
            rule:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                Rule is the Currently triggered rule'
              items:
                type: string
              type: array
            storageUsage:
              additionalProperties:
                type: string
              description: storage usage
              type: object
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
