apiVersion: v1
kind: Service
metadata:
  name: scale-operator
  namespace: sldb-admin
spec:
  selector:
    name: scale-operator
  ports:
    - protocol: TCP
      port: 8028
      targetPort: 8028
  clusterIP: None
