{{- if (hasKey .Values.scheduler "create" | ternary .Values.scheduler.create true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if eq .Values.appendReleaseSuffix true}}
  name: {{ .Values.scheduler.schedulerName }}-{{.Release.Name}}
  {{- else }}
  name: {{ .Values.scheduler.schedulerName }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: scheduler
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: scheduler
    spec:
    {{- if .Values.scheduler.serviceAccount }}
      serviceAccount: {{ .Values.scheduler.serviceAccount }}
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
  {{ toYaml .Values.imagePullSecrets | indent 6 }}
    {{- end }}
      containers:
      - name: {{ .Values.scheduler.schedulerName }}
        image: {{ .Values.operatorImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
        command:
          - /usr/local/bin/tidb-scheduler
          - -v={{ .Values.scheduler.logLevel }}
          - -port=10262
        {{- if .Values.features }}
          - -features={{ join "," .Values.features }}
        {{- end }}
      {{- if and (ne .Values.timezone "UTC") (ne .Values.timezone "") }}
        env:
        - name: TZ
          value: {{ .Values.timezone | default "UTC" }}
      {{- end }}
      - name: lvm-scheduler
        image: {{ required "scheduler.kubeSchedulerImageName is required" .Values.scheduler.kubeSchedulerImageName }}:{{- template "kube-scheduler.image_tag" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
        command:
        - lvm-scheduler
        - --config=/scheduler/scheduler-config.yaml
        - --v=3
        - --policy-configmap-namespace=tidb-admin
      {{- if and (ne .Values.timezone "UTC") (ne .Values.timezone "") }}
        env:
        - name: TZ
          value: {{ .Values.timezone | default "UTC" }}
      {{- end }}
        volumeMounts:
        - mountPath: /scheduler
          name: scheduler-config
    {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: scheduler-config
        name: scheduler-config
    {{- with .Values.scheduler.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.scheduler.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
